/**
 * 出力 HTML に埋め込む定型文言のロケール表。
 * 既定は日本語（ja）。定義ファイルの lang フィールドで切り替える。
 * 検証エラー・CLI メッセージは書き手向けのため対象外（日本語のまま）。
 */

export type Lang = "ja" | "en";

export interface Locale {
  /** <html lang="..."> */
  htmlLang: string;
  /** ヘッダーのメタ情報 */
  version: string;
  generated: string;
  metaSeparator: string;
  /** 見出し・目次 */
  flowsHeading: string;
  screensHeading: string;
  /** 凡例 */
  legendTitle: string;
  /** <li> の中身（強調タグ込み） */
  legendItems: string[];
  /** 画面カタログ */
  appearsIn: string;
  /** Gherkin 表 */
  behavior: string;
  given: string;
  when: string;
  then: string;
  and: string;
  /** ホットスポット・ミニチュアの title 属性 */
  gotoTitle: (target: string) => string;
  externalTitle: string;
  thumbTitle: string;
  /** フッター */
  footer: string;
}

export const LOCALES: Record<Lang, Locale> = {
  ja: {
    htmlLang: "ja",
    version: "版",
    generated: "生成",
    metaSeparator: " ／ ",
    flowsHeading: "業務フロー",
    screensHeading: "画面カタログ",
    legendTitle: "この資料の読み方",
    legendItems: [
      "<strong>業務フロー</strong>: 画面の縮小図と矢印で「誰が・どの画面で・何をすると・どうなるか」を表します。矢印の上が<strong>操作</strong>、下が<strong>システムの応答</strong>です。",
      "<strong>ふるまい表</strong>: 各フローの下にある「前提・操作・結果」の表は、開発で使うテストシナリオ（Gherkin）と1対1で対応します。",
      "<strong>画面カタログ</strong>: フロー中の縮小図をクリックすると、その画面の実寸ワイヤーフレームへ移動します。",
      "<strong>青い枠のボタン・リンク</strong>はクリックできるホットスポットです。クリックすると遷移先の画面へ移動し、移動先が一瞬ハイライトされます。",
      "<strong>⚙ の角丸ボックス</strong>は画面を持たない処理（バッチ・自動化など）を表します。下のラベルは処理の主体です。",
      "<strong>↗</strong> は外部サービスへの遷移（このワイヤーフレームの範囲外）を表します。",
      "<strong>黒い枠</strong>は端末（CLI）画面です。<code>$</code> はコマンド、<code>?</code> は対話プロンプトを表します。",
      "①②… の印は画面下の注釈と対応します。",
    ],
    appearsIn: "登場するフロー",
    behavior: "ふるまい（Given / When / Then）",
    given: "前提",
    when: "操作",
    then: "結果",
    and: "かつ",
    gotoTitle: (target) => `クリックで「${target}」へ移動`,
    externalTitle: "外部サービスへ移動",
    thumbTitle: "クリックで画面の詳細へ",
    footer: "Generated by flow-wireframe — 定義(JSON)と出力(HTML)は1対1で対応します",
  },
  en: {
    htmlLang: "en",
    version: "Version",
    generated: "Generated",
    metaSeparator: " / ",
    flowsHeading: "User flows",
    screensHeading: "Screen catalog",
    legendTitle: "How to read this document",
    legendItems: [
      "<strong>User flows</strong>: thumbnails and arrows show who does what on which screen, and what happens. Above each arrow is the <strong>action</strong>; below is the <strong>system response</strong>.",
      "<strong>Behavior tables</strong>: the Given / When / Then table under each flow maps 1-to-1 to the Gherkin scenarios used in development.",
      "<strong>Screen catalog</strong>: click any thumbnail in a flow to jump to the full-size wireframe of that screen.",
      "<strong>Buttons and links with a blue outline</strong> are clickable hotspots. Clicking one jumps to the target screen, which is briefly highlighted.",
      "<strong>Rounded boxes with ⚙</strong> are steps without a screen (batch jobs, automation). The label below shows who or what performs them.",
      "<strong>↗</strong> marks a transition to an external service (outside the scope of this wireframe).",
      "<strong>Dark frames</strong> are terminal (CLI) screens. <code>$</code> marks a command and <code>?</code> an interactive prompt.",
      "Marks like ①②… correspond to the numbered notes below each screen.",
    ],
    appearsIn: "Appears in",
    behavior: "Behavior (Given / When / Then)",
    given: "Given",
    when: "When",
    then: "Then",
    and: "And",
    gotoTitle: (target) => `Click to go to "${target}"`,
    externalTitle: "Goes to an external service",
    thumbTitle: "Click to see this screen in detail",
    footer: "Generated by flow-wireframe — the JSON definition and this HTML correspond 1-to-1",
  },
};
